import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "te" | "hi";

interface LanguageContextProps {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

// Rich, comprehensive mapping of English labels, headers, and buttons to Telugu and Hindi
const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {}, // English serves as fallback and keys
  te: {
    // 1. Splash Screen & Role Selection
    "Panchayat Digital Gateway": "పంచాయతీ డిజిటల్ గేట్‌వే",
    "Digital Complaint Gateway": "డిజిటల్ ఫిర్యాదు గేట్‌వే",
    "Village Complaint Desk": "గ్రామ ఫిర్యాదుల విభాగం",
    "Empowering citizens with AI-driven reporting, real-time tracking, GIS ward mapping, and transparent administration. Register issues & earn rewards.": "AI-ఆధారిత రిపోర్టింగ్, నిజ-సమయ ట్రాకింగ్, GIS వార్డ్ మ్యాపింగ్ మరియు పారదర్శక పరిపాలనతో పౌరులను శక్తివంతం చేయడం. సమస్యలను నమోదు చేయండి & రివార్డులను పొందండి.",
    "Get Started": "ప్రారంభించండి",
    "Citizen": "పౌరుడు",
    "Administrator": "అడ్మినిస్ట్రేటర్",
    "Panchayat Administration Portal": "పంచాయతీ పరిపాలన పోర్టల్",
    "District Hub": "జిల్లా కేంద్రం",
    "Contact Helpdesk": "సహాయ కేంద్రం",
    "Portal Login": "పోర్టల్ లాగిన్",
    "Enter Portal": "పోర్టల్‌లోకి ప్రవేశించండి",
    "Sign In to Portal": "పోర్టల్‌కు సైన్ ఇన్ చేయండి",
    "Email Address": "ఇమెయిల్ చిరునామా",
    "Password": "పాస్‌వర్డ్",
    "Forgot Password?": "పాస్‌వర్డ్ మర్చిపోయారా?",
    "Remember me": "నన్ను గుర్తుంచుకో",
    "Continue with Google": "గూగుల్‌తో కొనసాగండి",
    "Not an Admin?": "అడ్మిన్ కాదా?",
    "Sign In as Citizen": "పౌరుడిగా సైన్ ఇన్ చేయండి",
    "Terms of Service": "సేవా నిబంధనలు",
    "Privacy Policy": "గోప్యతా విధానం",
    "Search Ward": "వార్డును వెతకండి",
    "Check ward status": "వార్డు స్థితిని తనిఖీ చేయండి",
    "News & Notices": "వార్తలు & నోటీసులు",
    "Official Notices": "అధికారిక నోటీసులు",
    "Live Village Updates": "లైవ్ గ్రామ నవీకరణలు",
    "All Village Updates": "అన్ని గ్రామ నవీకరణలు",
    "Search Notices...": "నోటీసులు వెతకండి...",

    // 2. Main Layout & Dashboard Navigation
    "Panchayat Citizen Hub": "పంచాయతీ పౌర కేంద్రం",
    "Citizen Dashboard": "పౌర డ్యాష్‌బోర్డ్",
    "Logout": "లాగ్అవుట్",
    "Feed": "ఫీడ్",
    "Map View": "మ్యాప్ వీక్షణ",
    "Leaderboard": "లీడర్‌బోర్డ్",
    "Social Hub": "సామాజిక కేంద్రం",
    "Notifications": "నోటిఫికేషన్లు",
    "File Complaint": "ఫిర్యాదు చేయండి",
    "Total Complaints": "మొత్తం ఫిర్యాదులు",
    "Total Resolved": "మొత్తం పరిష్కరించబడినవి",
    "Active Pending": "యాక్టివ్ పెండింగ్",
    "Resolution Rate": "పరిష్కార రేటు",
    "Complaints Feed": "ఫిర్యాదుల ఫీడ్",
    "Panchayat Ward Map": "పంచాయతీ వార్డు మ్యాప్",
    "Leaderboard & Rewards": "లీడర్‌బోర్డ్ & రివార్డులు",
    "Alerts": "హెచ్చరికలు",
    "Go Back / Exit": "తిరిగి వెళ్ళండి",
    "Report New Issue": "కొత్త ఫిర్యాదు చేయండి",
    "Panchayat": "పంచాయతీ",
    "Home": "హోమ్",
    "Services": "సేవలు",
    "How It Works": "ఇది ఎలా పనిచేస్తుంది",
    "Login / Register": "లాగిన్ / రిజిస్టర్",
    "Your Issue,": "మీ సమస్య,",
    "Our Responsibility": "మా బాధ్యత",
    "Nizamabad Division, Telangana": "నిజామాబాద్ డివిజన్, తెలంగాణ",
    "Impact Rank": "ప్రభావం ర్యాంక్",
    "Officer Profile": "అధికారి ప్రొఫైల్",
    "Citizen Profile": "పౌరుడి ప్రొఫైల్",

    // 3. Issue Filters & Categories
    "All": "అన్నీ",
    "Roads & Potholes": "రోడ్లు & గుంతలు",
    "Water & Sanitation": "నీరు & పారిశుధ్యం",
    "Streetlights & Power": "వీధి దీపాలు & విద్యుత్",
    "Waste & Garbage": "వ్యర్థాలు & చెత్త",
    "Public Infrastructure": "ప్రజా మౌలిక సదుపాయాలు",
    "Other Community Issues": "ఇతర పౌర సమస్యలు",
    "Filter by Category": "వర్గం వారీగా వడపోత",
    "Filter by Status": "స్థితి వారీగా వడపోత",
    "Filter by Ward": "వార్డు వారీగా వడపోత",
    "Search complaints...": "ఫిర్యాదులను వెతకండి...",
    "Resolved": "పరిష్కరించబడింది",
    "Pending": "పెండింగ్",
    "In Progress": "పురోగతిలో ఉంది",
    "Submitted": "సమర్పించబడింది",
    "Verified": "ధృవీకరించబడింది",
    "Assigned": "కేటాయించబడింది",

    // 4. Issue Detail Overlay & Interactive Actions
    "Complaint Details": "ఫిర్యాదు వివరాలు",
    "Reported by": "నివేదించిన వారు",
    "Ward Name": "వార్డు పేరు",
    "Location": "ప్రాంతం",
    "Created": "సృష్టించబడింది",
    "Urgency": "అవసరం",
    "Upvote": "అప్ఓట్",
    "Verify Issue": "సమస్యను ధృవీకరించండి",
    "Upvoted": "అప్ఓట్ చేయబడింది",
    "Verified Issue": "సమస్య ధృవీకరించబడింది",
    "Flags": "ఫ్లాగ్స్",
    "Flag Issue": "సమస్యను ఫ్లాగ్ చేయండి",
    "Official Resolution Details": "అధికారిక పరిష్కార వివరాలు",
    "Assigned Department": "కేటాయించిన విభాగం",
    "Official Remarks": "అధికారిక వ్యాఖ్యలు",
    "Interactive Map": "ఇంటరాక్టివ్ మ్యాప్",
    "Write a comment...": "కామెంట్ రాయండి...",
    "Post Comment": "కామెంట్ చేయండి",
    "Comments": "కామెంట్లు",

    // 5. Issue Reporting Form
    "File New Complaint": "కొత్త ఫిర్యాదు చేయండి",
    "Select your preferred communication media to submit your complaint.": "మీ ఫిర్యాదును సమర్పించడానికి మీ ప్రాధాన్యత కమ్యూనికేషన్ మీడియాను ఎంచుకోండి.",
    "Option 1: Guided Form": "ఆప్షన్ 1: గైడెడ్ ఫారమ్",
    "Traditional structural reporting with categorization, severity selection, ward mapping and file attachments.": "వర్గీకరణ, తీవ్రత ఎంపిక, వార్డ్ మ్యాపింగ్ మరియు ఫైల్ అటాచ్‌మెంట్‌లతో సాంప్రదాయ నిర్మాణాత్మక రిపోర్టింగ్.",
    "Option 2: Chat Assistant": "ఆప్షన్ 2: చాట్ అసిస్టెంట్",
    "Interactive conversational bot. Describe your grievance naturally and let our system auto-categorize it.": "ఇంటరాక్టివ్ సంభాషణ బాట్. మీ సమస్యను సహజంగా వివరించండి మరియు మా సిస్టమ్ దానిని స్వయంచాలకంగా వర్గీకరిస్తుంది.",
    "Option 3: Voice Dictation": "ఆప్షన్ 3: వాయిస్ డిక్టేషన్",
    "Hands-free speech-to-text recording. Transcribe native regional dialects and language automatically.": "హ్యాండ్స్-ఫ్రీ స్పీచ్-టు-టెక్స్ట్ రికార్డింగ్. స్థానిక ప్రాంతీయ మాండలికాలు మరియు భాషను స్వయంచాలకంగా అనువదించండి.",
    "Submit Complaint": "ఫిర్యాదు సమర్పించండి",
    "Complaint Title": "ఫిర్యాదు శీర్షిక",
    "Enter a short, descriptive title": "చిన్న, వివరణాత్మక శీర్షికను నమోదు చేయండి",
    "Issue Category": "సమస్య వర్గం",
    "Select Category": "వర్గాన్ని ఎంచుకోండి",
    "Urgency Level": "అవసరమైన స్థాయి",
    "Low": "తక్కువ",
    "Medium": "మధ్యస్థం",
    "High": "ఎక్కువ",
    "Critical": "తీవ్రమైనది",
    "Detailed Description": "వివరణాత్మక వివరణ",
    "Describe the issue in detail to help Panchayat resolving officers understand the situation...": "పంచాయితీ పరిష్కార అధికారులు పరిస్థితిని అర్థం చేసుకోవడానికి సమస్యను వివరంగా వివరించండి...",
    "Select Ward Area": "వార్డు ప్రాంతాన్ని ఎంచుకోండి",
    "Select Ward": "వార్డును ఎంచుకోండి",
    "Address Description": "చిరునామా వివరణ",
    "Specify exact landmark or street address": "ఖచ్చితమైన మైలురాయి లేదా వీధి చిరునామాను పేర్కొనండి",
    "Interactive GPS Location Mapping": "ఇంటరాక్టివ్ GPS స్థాన మ్యాపింగ్",
    "Drag the marker to pinpoint the exact issue location": "ఖచ్చితమైన సమస్య స్థానాన్ని గుర్తించడానికి మార్కర్‌ను లాగండి",
    "Upload Proof (Image / Video)": "రుజువును అప్‌లోడ్ చేయండి (చిత్రం / వీడియో)",
    "Drag & drop image/video here, or click to browse": "చిత్రం/వీడియోను ఇక్కడ డ్రాగ్ & డ్రాప్ చేయండి లేదా బ్రౌజ్ చేయడానికి క్లిక్ చేయండి",
    "Optional: Submit Anonymously": "ఐచ్ఛికం: అనామకంగా సమర్పించండి",
    "Hide your name from the public feed": "పబ్లిక్ ఫీడ్ నుండి మీ పేరును దాచండి",
    "Back to Options": "తిరిగి వెళ్ళండి",
    "Option 1": "ఆప్షన్ 1",
    "Option 2": "ఆప్షన్ 2",
    "Option 3": "ఆప్షన్ 3",
    "Option 4": "ఆప్షన్ 4",
    "Camera Live Snap": "కెమెరా లైవ్ స్నాప్",
    "Activate device webcam to capture photos or live video proof of community damages directly on the spot.": "సమస్యలు జరిగిన ప్రదేశంలోనే ఫోటోలు లేదా ప్రత్యక్ష వీడియో సాక్ష్యాలను సంగ్రహించడానికి మీ డివైస్ వెబ్‌క్యామ్‌ను యాక్టివేట్ చేయండి.",
    "Open On-Site Lens": "ఆన్-సైట్ లెన్స్ తెరవండి",
    "Voice Dictation": "వాయిస్ డిక్టేషన్",
    "Activate microphone to dictate details. Gram AI transcribes your local speech into an organized text report.": "సమస్య వివరాలను డిక్టేట్ చేయడానికి మైక్రోఫోన్‌ను యాక్టివేట్ చేయండి. మా గ్రామ AI మీ ప్రసంగాన్ని క్రమబద్ధమైన వచన నివేదికగా మారుస్తుంది.",
    "Activate Dictation": "డిక్టేషన్ ప్రారంభించండి",
    "Standard Text Form": "ప్రామాణిక వచన ఫారమ్",
    "Submit your concern manually. Fill detailed text, pin coordinates on the map, choose presets, or file anonymously.": "మీ సమస్యను మాన్యువల్‌గా సమర్పించండి. వివరాలను పూరించండి, మ్యాప్‌లో పిన్ చేయండి, ప్రీసెట్‌లను ఎంచుకోండి లేదా అజ్ఞాతంగా దాఖలు చేయండి.",
    "Write Manual Form": "మాన్యువల్‌గా రాయండి",
    "Direct Officer Call": "అధికారితో నేరుగా కాల్",
    "Need immediate resolution? View direct mobile numbers of village Panchayat leaders and engineers to call them.": "తక్షణ పరిష్కారం కావాలా? గ్రామానికి చెందిన పంచాయతీ నాయకులు మరియు ఇంజనీర్ల మొబైల్ నంబర్లను వీక్షించండి మరియు నేరుగా కాల్ చేయండి.",
    "View Panchayat Directory": "పంచాయతీ డైరెక్టరీని వీక్షించండి",
    "📌 Panchayat Digital Complaint Desk acts as an official liaison system. Complaints posted via Option 1, 2, and 3 are published on the village civic feed for live tracking and administrative points allocation.": "📌 పంచాయతీ డిజిటల్ ఫిర్యాదు డెస్క్ అధికారిక అనుసంధాన వ్యవస్థగా పనిచేస్తుంది. ఆప్షన్ 1, 2 మరియు 3 ద్వారా పోస్ట్ చేయబడిన ఫిర్యాదులు పాయింట్ల కేటాయింపు మరియు లైవ్ ట్రాకింగ్ కోసం గ్రామ పౌర ఫీడ్‌లో ప్రచురించబడతాయి.",

    // 6. Voice Dictation Assistant
    "Voice Dictation Assistant": "వాయిస్ డిక్టేషన్ సహాయకుడు",
    "Record your voice, and our real-time transcribing engine will write the complaint for you.": "మీ వాయిస్‌ని రికార్డ్ చేయండి మరియు మా నిజ-సమయ అనువాద ఇంజిన్ మీ కోసం ఫిర్యాదును వ్రాస్తుంది.",
    "Start Dictation": "డిక్టేషన్ ప్రారంభించండి",
    "Stop & Transcribe": "ఆపి ట్రాన్స్క్రైబ్ చేయండి",
    "Speaking Real-time Transcript Preview:": "మాట్లాడుతున్న నిజ-సమయ ట్రాన్స్క్రిప్ట్ ప్రివ్యూ:",
    "Listening... Start speaking to see text generation...": "వింటున్నాము... వచనం ఉత్పత్తి కావడానికి మాట్లాడటం ప్రారంభించండి...",
    "Your transcript text will generate here once you click Stop. You can manually tweak or edit it here as well.": "మీరు స్టాప్ క్లిక్ చేసిన తర్వాత మీ ట్రాన్స్క్రిప్ట్ వచనం ఇక్కడ ఉత్పత్తి అవుతుంది. మీరు దీన్ని ఇక్కడ కూడా మాన్యువల్‌గా సవరించవచ్చు.",
    "Append to Description": "వివరణకు జోడించండి",

    // 7. Social Hub & Leaderboard
    "Panchayat Social Wall": "పంచాయతీ సామాజిక గోడ",
    "Village Community Corner": "గ్రామ సమాజ మూల",
    "Interact with co-citizens, share community initiatives, and voice ideas. Only constructive topics permitted.": "తోటి పౌరులతో సంభాషించండి, సమాజ కార్యక్రమాలను పంచుకోండి మరియు ఆలోచనలను తెలియజేయండి. నిర్మాణాత్మక అంశాలు మాత్రమే అనుమతించబడతాయి.",
    "Write something to the village community wall...": "గ్రామ సమాజ గోడకు ఏదైనా రాయండి...",
    "Post to Wall": "గోడపై పోస్ట్ చేయండి",
    "Anonymous": "అనామకుడు",
    "Likes": "లైకులు",
    "Panchayat Leaderboard": "పంచాయతీ లీడర్‌బోర్డ్",
    "Top Active Citizen Contributors": "అత్యంత చురుకైన పౌర సహకారులు",
    "Rankings are updated dynamically based on approved complaint filings (+15 points) and valid issue verifications (+5 points).": "ఆమోదించబడిన ఫిర్యాదు దాఖలు (+15 పాయింట్లు) మరియు చెల్లుబాటు అయ్యే సమస్య ధృవీకరణల (+5 పాయింట్లు) ఆధారంగా ర్యాంకింగ్‌లు డైనమిక్‌గా నవీకరించబడతాయి.",
    "Rank": "ర్యాంక్",
    "Citizen Name": "పౌరుడి పేరు",
    "Points Earned": "పొందిన పాయింట్లు",
    "Issues": "సమస్యలు",
    "Coins Earned": "పొందిన నాణేలు",
    "Panchayat Level": "పంచాయతీ స్థాయి",

    // 8. Notifications
    "Panchayat Notice Inbox": "పంచాయతీ నోటీస్ ఇన్‌బాక్స్",
    "Live dispatch SMS & push channels": "లైవ్ డిస్పాచ్ SMS & పుష్ ఛానెల్‌లు",
    "Mark All as Read": "అన్నీ చదివినట్లుగా గుర్తించండి",
    "No notifications yet.": "ఇంకా నోటిఫికేషన్‌లు లేవు.",

    // General & Dashboard Profile
    "Ward": "వార్డు",
    "Coins": "నాణేలు",
    "Ward Area": "వార్డు ప్రాంతం",
    "Verified Citizen": "ధృవీకరించబడిన పౌరుడు",
    "District Commissioner": "జిల్లా కమిషనర్",
    "Panchayat Officer": "పంచాయతీ అధికారి",
    "Admin Controls": "అడ్మిన్ నియంత్రణలు",

    // New Translations: Alerts, News, Social Hub, Admin
    "Live Alert & Notification logs": "లైవ్ అలర్ట్ & నోటిఫికేషన్ లాగ్‌లు",
    "This terminal tracks simulated multi-channel Push alerts and SMS dispatch logs in Nizamabad.": "ఈ టెర్మినల్ నిజామాబాద్‌లో సిమ్యులేట్ చేయబడిన మల్టీ-ఛానల్ పుష్ అలర్ట్‌లు మరియు SMS డిస్పాచ్ లాగ్‌లను ట్రాక్ చేస్తుంది.",
    "Mark all read": "అన్నీ చదివినట్లుగా గుర్తించండి",
    "SMS Logs": "SMS లాగ్‌లు",
    "Clear": "తీసివేయండి",
    "Your Inbox is quiet. No notifications found.": "మీ ఇన్‌బాక్స్ ప్రశాంతంగా ఉంది. నోటిఫికేషన్‌లు కనుగొనబడలేదు.",
    "Looking for Official Panchayat Announcements?": "అధికారిక పంచాయతీ ప్రకటనల కోసం చూస్తున్నారా?",
    "Official Channel": "అధికారిక ఛానెల్",
    "While this Social Hub is a friendly space for open community discussion among citizens, official resolutions, emergency alerts, and department announcements have a dedicated home under the Alerts section.": "ఈ సామాజిక హబ్ పౌరుల మధ్య బహిరంగ చర్చకు అనుకూలమైన స్థలం అయినప్పటికీ, అధికారిక తీర్మానాలు, అత్యవసర హెచ్చరికలు మరియు విభాగాల ప్రకటనలకు హెచ్చరికల విభాగంలో ప్రత్యేక స్థలం ఉంది.",
    "Check Alerts Section": "హెచ్చరికల విభాగాన్ని తనిఖీ చేయండి",
    "Share Gram Discussion": "గ్రామ చర్చను పంచుకోండి",
    "What is happening in Nizamabad? Share announcements, alerts or opinions. Use #hashtags to tag topics, or @Sarpanch to notify officials.": "నిజామాబాద్‌లో ఏం జరుగుతోంది? ప్రకటనలు, హెచ్చరికలు లేదా అభిప్రాయాలను పంచుకోండి. అంశాలను ట్యాగ్ చేయడానికి #hashtags ఉపయోగించండి లేదా అధికారులకు తెలియజేయడానికి @Sarpanch ఉపయోగించండి.",
    "Supports automatic hashtag recognition and staff tagging alerts.": "స్వయంచాలక హ్యాష్‌ట్యాగ్ గుర్తింపు మరియు సిబ్బంది ట్యాగింగ్ హెచ్చరికలకు మద్దతు ఇస్తుంది.",
    "Photo evidence ready": "ఫోటో సాక్ష్యం సిద్ధంగా ఉంది",
    "Video evidence evidence ready": "వీడియో సాక్ష్యం సిద్ధంగా ఉంది",
    "Attach Photo/Video": "ఫోటో/వీడియో జతచేయండి",
    "GPS Tagged": "GPS ట్యాగ్ చేయబడింది",
    "Tag Ward Location": "వార్డ్ స్థానాన్ని ట్యాగ్ చేయండి",
    "Clear Attach": "జోడింపును క్లియర్ చేయండి",
    "Post anonymously (Mask identity)": "అనామకంగా పోస్ట్ చేయండి (గుర్తింపును దాచండి)",
    "Publishing...": "ప్రచురిస్తోంది...",
    "Publish to Social Hub": "సామాజిక హబ్‌కు ప్రచురించండి",
    "Popular Panchayat Topics": "ప్రసిద్ధ పంచాయతీ అంశాలు",
    "Panchayat Notice Board": "పంచాయతీ నోటీసు బోర్డు",
    "Panchayat News & Announcements": "పంచాయతీ వార్తలు & ప్రకటనలు",
    "Stay informed with active community news, local utility schedules, and administrative developments.": "క్రియాశీల కమ్యూనిటీ వార్తలు, స్థానిక వినియోగ షెడ్యూల్‌లు మరియు పరిపాలనా పరిణామాలతో సమాచారాన్ని పొందండి.",
    "Read Announcement": "ప్రకటన చదవండి",
    "Released by": "విడుదల చేసిన వారు",
    "Digital Portal Notice": "డిజిటల్ పోర్టల్ నోటీసు",
    "This is an official digital broadcast issued by the Gram Panchayat administrative wing. For complaint registration or quick queries regarding this announcement, please use the citizen interactive desk.": "ఇది గ్రామ పంచాయతీ పరిపాలనా విభాగం జారీ చేసిన అధికారిక డిజిటల్ ప్రసారం. ఈ ప్రకటనకు సంబంధించిన ఫిర్యాదుల నమోదు లేదా శీఘ్ర ప్రశ్నల కోసం, దయచేసి పౌర ఇంటరాక్టివ్ డెస్క్‌ను ఉపయోగించండి.",
    "Close Notice": "నోటీసును మూసివేయండి",
    "Sub-canal Drinking Water Pipeline Repair Completed": "సబ్-కెనాల్ త్రాగునీటి పైప్‌లైన్ మరమ్మత్తు పూర్తయింది",
    "Annual Gram Panchayat Budget & Electrification Approval": "వార్షిక గ్రామ పంచాయతీ బడ్జెట్ & విద్యుద్దీకరణ ఆమోదం",
    "Digital Land Records & Aadhaar Seeding Desk Opens": "డిజిటల్ ల్యాండ్ రికార్డ్స్ & ఆధార్ సీడింగ్ డెస్క్ ప్రారంభం",
    "Monsoon Preparedness Audit: Drainage Cleansing Drive": "రుతుపవనాల సన్నద్ధత ఆడిట్: డ్రైనేజీ శుభ్రపరిచే కార్యక్రమం",
    "Utilities": "వినియోగాలు",
    "Government": "ప్రభుత్వం",
    "Development": "అభివృద్ధి",
    "Events": "ఈవెంట్లు",
    "Gram Panchayat Online Services": "గ్రామ పంచాయతీ ఆన్‌లైన్ సేవలు",
    "empowering village self-governance via Digital India Initiative.": "డిజిటల్ ఇండియా చొరవ ద్వారా గ్రామ స్వపరిపాలనను శక్తివంతం చేయడం.",
    "Report local problems, track updates and help build a better community together.": "స్థానిక సమస్యలను నివేదించండి, నవీకరణలను ట్రాక్ చేయండి మరియు కలిసి మెరుగైన సమాజాన్ని నిర్మించడంలో సహాయపడండి.",
    "How Panchayat Online Works": "పంచాయతీ ఆన్‌లైన్ ఎలా పనిచేస్తుంది",
    "1. Report": "1. నివేదించండి",
    "Capture and report issues in your area with photos or videos.": "ఫోటోలు లేదా వీడియోలతో మీ ప్రాంతంలోని సమస్యలను సంగ్రహించండి మరియు నివేదించండి.",
    "2. AI Categorization": "2. AI వర్గీకరణ",
    "Our AI automatically categorizes and assigns the issue.": "మా AI స్వయంచాలకంగా సమస్యను వర్గీకరిస్తుంది మరియు కేటాయిస్తుంది.",
    "3. Track": "3. ట్రాక్ చేయండి",
    "Track the status of your reported issue in real time.": "మీరు నివేదించిన సమస్య స్థితిని నిజ సమయంలో ట్రాక్ చేయండి.",
    "4. Resolved": "4. పరిష్కరించబడింది",
    "Get updates and notifications when the issue is resolved.": "సమస్య పరిష్కరించబడినప్పుడు నవీకరణలు మరియు నోటిఫికేషన్‌లను పొందండి.",
    "Stay Updated": "నవీకరించబడి ఉండండి",
    "Subscribe to get updates and important announcements.": "నవీకరణలు మరియు ముఖ్యమైన ప్రకటనలను పొందడానికి సభ్యత్వాన్ని పొందండి.",
    "Enter your email": "మీ ఇమెయిల్ నమోదు చేయండి",
    "Subscribed!": "సభ్యత్వం పొందబడింది!",
    "Subscribe": "సభ్యత్వాన్ని పొందండి",
    "Follow Us": "మమ్మల్ని అనుసరించండి",
    "Panchayat Online. All rights reserved.": "పంచాయతీ ఆన్‌లైన్. అన్ని హక్కులు ప్రత్యేకించబడినవి.",
    "Help Center": "సహాయ కేంద్రం",
    "Back": "వెనుకకు",
    "Access Secure Portal": "సురక్షిత పోర్టల్‌ను యాక్సెస్ చేయండి",
    "Select your access role below to sign in or get started.": "సైన్ ఇన్ చేయడానికి లేదా ప్రారంభించడానికి దిగువన మీ యాక్సెస్ పాత్రను ఎంచుకోండి.",
    "Enter as Citizen": "పౌరుడిగా ప్రవేశించండి",
    "Enter as Panchayat Officer": "పంచాయతీ అధికారిగా ప్రవేశించండి",
    "Citizen Access": "పౌరుడి యాక్సెస్",
    "Officer Access": "అధికారి యాక్సెస్",
    "OTP Verification": "OTP ధృవీకరణ",
    "Enter your email credentials to access your secure profile.": "మీ సురక్షిత ప్రొఫైల్‌ను యాక్సెస్ చేయడానికి మీ ఇమెయిల్ ఆధారాలను నమోదు చేయండి.",
    "Authenticate instantly with a mobile verification code.": "మొబైల్ వెరిఫికేషన్ కోడ్‌తో తక్షణమే ప్రామాణీకరించండి.",
    "Forgot?": "మర్చిపోయారా?",
    "Verifying Access...": "యాక్సెస్‌ని ధృవీకరిస్తోంది...",
    "Secure Sign In": "సురక్షిత సైన్ ఇన్",
    "Sending OTP...": "OTP పంపుతోంది...",
    "Send OTP Code": "OTP కోడ్‌ను పంపండి",
    "Change Mobile": "మొబైల్ మార్చండి",
    "Demo OTP: 1234": "డెమో OTP: 1234",
    "Verifying OTP...": "OTPని ధృవీకరిస్తోంది...",
    "Verify & Login": "ధృవీకరించి లాగిన్ అవ్వండి",
    "Or Continue With": "లేదా దీనితో కొనసాగండి",
    "This calling feature works better in mobile phone": "ఈ కాలింగ్ ఫీచర్ మొబైల్ ఫోన్‌లో బాగా పనిచేస్తుంది",
    "Panchayat Emergency Helpline": "పంచాయతీ అత్యవసర హెల్ప్‌లైన్",
    "Initiate direct calls to village administration and maintenance directors instantly.": "గ్రామ పరిపాలన మరియు నిర్వహణ దర్శకులకు తక్షణమే నేరుగా కాల్స్ చేయండి.",
    "Simulate Call": "కాల్ సిమ్యులేట్ చేయండి",
    "Direct Dialer Link": "డైరెక్ట్ డయలర్ లింక్",
    "Emergency Warning:": "అత్యవసర హెచ్చరిక:",
    "If you are calling to report immediate threats (like active live electrical cables sparked by storms, major canal breaches flooding houses), please dial the Sarpanch or Sanitation officer immediately to dispatch emergency response squads.": "మీరు తక్షణ ముప్పులను (తుఫానుల వల్ల ఏర్పడే ప్రత్యక్ష విద్యుత్ కేబుల్స్, ఇళ్లను ముంచెత్తే ప్రధాన కాలువ గండ్లు వంటివి) నివేదించడానికి కాల్ చేస్తుంటే, దయచేసి అత్యవసర సహాయక బృందాలను పంపడానికి వెంటనే సర్పంచ్ లేదా పారిశుధ్య అధికారికి కాల్ చేయండి.",
    "Smt. Rajeshwari Devi": "శ్రీమతి రాజేశ్వరి దేవి",
    "Gram Panchayat Sarpanch (President)": "గ్రామ పంచాయతీ సర్పంచ్ (అధ్యక్షురాలు)",
    "Shri Mohan Rao": "శ్రీ మోహన్ రావు",
    "Panchayat Secretary (Administrative Head)": "పంచాయతీ కార్యదర్శి (పరిపాలనా అధిపతి)",
    "Smt. Lakshmi Bai": "శ్రీమతి లక్ష్మీ బాయి",
    "Health & Sanitation Inspector": "ఆరోగ్య మరియు పారిశుధ్య ఇన్స్పెక్టర్",
    "Shri Venkatesh Goud": "శ్రీ వెంకటేష్ గౌడ్",
    "Water Works & Electrical Engineer": "వాటర్ వర్క్స్ & ఎలక్ట్రికల్ ఇంజనీర్",
    "Shri Ramesh Kumar": "శ్రీ రమేష్ కుమార్",
    "Ward 1 & 2 Civic Representative": "వార్డు 1 & 2 పౌర ప్రతినిధి",
    "Available": "అందుబాటులో ఉన్నారు",
    "In Office": "కార్యాలయంలో ఉన్నారు",
    "On Field Patrol": "ఫీల్డ్ పెట్రోలింగ్‌లో ఉన్నారు",
    "Meeting": "సమావేశంలో ఉన్నారు"
  },
  hi: {
    // 1. Splash Screen & Role Selection
    "Panchayat Digital Gateway": "पंचायत डिजिटल गेटवे",
    "Digital Complaint Gateway": "डिजिटल शिकायत गेटवे",
    "Village Complaint Desk": "ग्राम शिकायत डेस्क",
    "Empowering citizens with AI-driven reporting, real-time tracking, GIS ward mapping, and transparent administration. Register issues & earn rewards.": "एआई-संचालित रिपोर्टिंग, रीयल-टाइम ट्रैकिंग, जीआईएस वार्ड मैपिंग और पारदर्शी प्रशासन के साथ नागरिकों को सशक्त बनाना। मुद्दों को दर्ज करें और पुरस्कार अर्जित करें।",
    "Get Started": "शुरू करें",
    "Citizen": "नागरिक",
    "Administrator": "प्रशासक",
    "Panchayat Administration Portal": "पंचायत प्रशासन पोर्टल",
    "District Hub": "जिला केंद्र",
    "Contact Helpdesk": "सहायता डेस्क",
    "Portal Login": "पोर्टल लॉगिन",
    "Enter Portal": "पोर्टल में प्रवेश करें",
    "Sign In to Portal": "पोर्टल में साइन इन करें",
    "Email Address": "ईमेल पता",
    "Password": "पासवर्ड",
    "Forgot Password?": "पासवर्ड भूल गए?",
    "Remember me": "मुझे याद रखें",
    "Continue with Google": "गूगल के साथ जारी रखें",
    "Not an Admin?": "प्रशासक नहीं हैं?",
    "Sign In as Citizen": "नागरिक के रूप में साइन इन करें",
    "Terms of Service": "सेवा की शर्तें",
    "Privacy Policy": "गोपनीयता नीति",
    "Search Ward": "वार्ड खोजें",
    "Check ward status": "वार्ड स्थिति जांचें",
    "News & Notices": "समाचार और नोटिस",
    "Official Notices": "आधिकारिक नोटिस",
    "Live Village Updates": "लाइव ग्राम अपडेट",
    "All Village Updates": "सभी ग्राम अपडेट",
    "Search Notices...": "नोटिस खोजें...",

    // 2. Main Layout & Dashboard Navigation
    "Panchayat Citizen Hub": "पंचायत नागरिक केंद्र",
    "Citizen Dashboard": "नागरिक डैशबोर्ड",
    "Logout": "लॉगआउट",
    "Feed": "फ़ीड",
    "Map View": "मानचित्र दृश्य",
    "Leaderboard": "लीडरबोर्ड",
    "Social Hub": "सामाजिक केंद्र",
    "Notifications": "सूचनाएं",
    "File Complaint": "शिकायत दर्ज करें",
    "Total Complaints": "कुल शिकायतें",
    "Total Resolved": "कुल हल",
    "Active Pending": "सक्रिय लंबित",
    "Resolution Rate": "समाधान दर",
    "Complaints Feed": "शिकायत फ़ीड",
    "Panchayat Ward Map": "पंचायत वार्ड मानचित्र",
    "Leaderboard & Rewards": "लीडरबोर्ड और पुरस्कार",
    "Alerts": "अलर्ट",
    "Go Back / Exit": "वापस जाएं",
    "Report New Issue": "नई शिकायत दर्ज करें",
    "Panchayat": "पंचायत",
    "Home": "होम",
    "Services": "सेवाएं",
    "How It Works": "यह कैसे काम करता है",
    "Login / Register": "लॉगिन / पंजीकरण",
    "Your Issue,": "आपकी समस्या,",
    "Our Responsibility": "हमारी जिम्मेदारी",
    "Nizamabad Division, Telangana": "निज़ामाबाद संभाग, तेलंगाना",
    "Impact Rank": "प्रभाव रैंक",
    "Officer Profile": "अधिकारी प्रोफ़ाइल",
    "Citizen Profile": "नागरिक प्रोफ़ाइल",

    // 3. Issue Filters & Categories
    "All": "सभी",
    "Roads & Potholes": "सड़कें और गड्ढे",
    "Water & Sanitation": "जल और स्वच्छता",
    "Streetlights & Power": "स्ट्रीटलाइट और बिजली",
    "Waste & Garbage": "कचरा और कचरा प्रबंधन",
    "Public Infrastructure": "सार्वजनिक बुनियादी ढांचा",
    "Other Community Issues": "अन्य नागरिक मुद्दे",
    "Filter by Category": "श्रेणी के अनुसार फ़िल्टर करें",
    "Filter by Status": "स्थिति के अनुसार फ़िल्टर करें",
    "Filter by Ward": "वार्ड के अनुसार फ़िल्टर करें",
    "Search complaints...": "शिकायतें खोजें...",
    "Resolved": "हल किया गया",
    "Pending": "लंबित",
    "In Progress": "प्रगति पर है",
    "Submitted": "जमा किया गया",
    "Verified": "सत्यापित",
    "Assigned": "सौंपा गया",

    // 4. Issue Detail Overlay & Interactive Actions
    "Complaint Details": "शिकायत विवरण",
    "Reported by": "रिपोर्टकर्ता",
    "Ward Name": "वार्ड का नाम",
    "Location": "स्थान",
    "Created": "बनाया गया",
    "Urgency": "त्वरितता",
    "Upvote": "अपवोट",
    "Verify Issue": "मुद्दे को सत्यापित करें",
    "Upvoted": "अपवोट किया गया",
    "Verified Issue": "मुद्दा सत्यापित है",
    "Flags": "फ्लैग",
    "Flag Issue": "फ्लैग करें",
    "Official Resolution Details": "आधिकारिक समाधान विवरण",
    "Assigned Department": "सौंपा गया विभाग",
    "Official Remarks": "आधिकारिक टिप्पणी",
    "Interactive Map": "इंटरएक्टिव मानचित्र",
    "Write a comment...": "टिप्पणी लिखें...",
    "Post Comment": "टिप्पणी पोस्ट करें",
    "Comments": "टिप्पणियाँ",

    // 5. Issue Reporting Form
    "File New Complaint": "नई शिकायत दर्ज करें",
    "Select your preferred communication media to submit your complaint.": "अपनी शिकायत दर्ज करने के लिए अपना पसंदीदा संचार माध्यम चुनें।",
    "Option 1: Guided Form": "विकल्प 1: निर्देशित फ़ॉर्म",
    "Traditional structural reporting with categorization, severity selection, ward mapping and file attachments.": "श्रेणीकरण, गंभीरता चयन, वार्ड मैपिंग और फ़ाइल अटैचमेंट के साथ पारंपरिक रिपोर्टिंग।",
    "Option 2: Chat Assistant": "विकल्प 2: चैट सहायक",
    "Interactive conversational bot. Describe your grievance naturally and let our system auto-categorize it.": "इंटरएक्टिव चैटबॉट। अपनी समस्या स्वाभाविक रूप से बताएं और हमारी प्रणाली इसे स्वचालित रूप से वर्गीकृत करेगी।",
    "Option 3: Voice Dictation": "विकल्प 3: वॉयस श्रुतलेख",
    "Hands-free speech-to-text recording. Transcribe native regional dialects and language automatically.": "हैंड्स-फ्री स्पीच-टू-टेक्स्ट रिकॉर्डिंग। क्षेत्रीय बोलियों और भाषाओं को स्वचालित रूप से अनुवाद करें।",
    "Submit Complaint": "शिकायत जमा करें",
    "Complaint Title": "शिकायत का शीर्षक",
    "Enter a short, descriptive title": "एक संक्षिप्त, वर्णनात्मक शीर्षक दर्ज करें",
    "Issue Category": "मुद्दा श्रेणी",
    "Select Category": "श्रेणी चुनें",
    "Urgency Level": "त्वरितता स्तर",
    "Low": "कम",
    "Medium": "मध्यम",
    "High": "उच्च",
    "Critical": "गंभीर",
    "Detailed Description": "विस्तृत विवरण",
    "Describe the issue in detail to help Panchayat resolving officers understand the situation...": "पंचायती समाधान अधिकारियों को स्थिति समझाने के लिए समस्या का विस्तार से वर्णन करें...",
    "Select Ward Area": "वार्ड क्षेत्र चुनें",
    "Select Ward": "वार्ड चुनें",
    "Address Description": "पता विवरण",
    "Specify exact landmark or street address": "सटीक लैंडमार्क या सड़क का पता निर्दिष्ट करें",
    "Interactive GPS Location Mapping": "इंटरएक्टिव जीपीएस स्थान मैपिंग",
    "Drag the marker to pinpoint the exact issue location": "सटीक समस्या स्थान को इंगित करने के लिए मार्कर खींचें",
    "Upload Proof (Image / Video)": "प्रमाण अपलोड करें (छवि / वीडियो)",
    "Drag & drop image/video here, or click to browse": "यहाँ छवि/वीडियो खींचें और छोड़ें, या ब्राउज़ करने के लिए क्लिक करें",
    "Optional: Submit Anonymously": "वैकल्पिक: गुमनाम रूप से जमा करें",
    "Hide your name from the public feed": "सार्वजनिक फ़ीड से अपना नाम छिपाएं",
    "Back to Options": "विकल्पों पर वापस जाएं",
    "Option 1": "विकल्प 1",
    "Option 2": "विकल्प 2",
    "Option 3": "विकल्प 3",
    "Option 4": "विकल्प 4",
    "Camera Live Snap": "कैमरा लाइव स्नैप",
    "Activate device webcam to capture photos or live video proof of community damages directly on the spot.": "सामुदायिक क्षतियों के लाइव फोटो या वीडियो प्रमाण को सीधे घटना स्थल पर कैप्चर करने के लिए डिवाइस वेबकैम सक्रिय करें।",
    "Open On-Site Lens": "ऑन-साइट लेंस खोलें",
    "Voice Dictation": "वॉयस श्रुतलेख",
    "Activate microphone to dictate details. Gram AI transcribes your local speech into an organized text report.": "विवरण निर्देशित करने के लिए माइक्रोफ़ोन सक्रिय करें। ग्राम एआई आपके स्थानीय भाषण को एक व्यवस्थित पाठ रिपोर्ट में अनुवादित करता है।",
    "Activate Dictation": "डिक्टेशन सक्रिय करें",
    "Standard Text Form": "मानक पाठ फ़ॉर्म",
    "Submit your concern manually. Fill detailed text, pin coordinates on the map, choose presets, or file anonymously.": "अपनी चिंता मैन्युअल रूप से सबमिट करें। विस्तृत विवरण भरें, मानचित्र पर निर्देशांक पिन करें, प्रीसेट चुनें, या गुमनाम रूप से दर्ज करें।",
    "Write Manual Form": "मैन्युअल फॉर्म भरें",
    "Direct Officer Call": "अधिकारी से सीधी कॉल",
    "Need immediate resolution? View direct mobile numbers of village Panchayat leaders and engineers to call them.": "त्वरित समाधान चाहिए? ग्राम पंचायत नेताओं और इंजीनियरों के सीधे मोबाइल नंबर देखें और उन्हें कॉल करें।",
    "View Panchayat Directory": "पंचायत निर्देशिका देखें",
    "📌 Panchayat Digital Complaint Desk acts as an official liaison system. Complaints posted via Option 1, 2, and 3 are published on the village civic feed for live tracking and administrative points allocation.": "📌 पंचायत डिजिटल शिकायत डेस्क एक आधिकारिक संपर्क प्रणाली के रूप में कार्य करता है। विकल्प 1, 2 और 3 के माध्यम से पोस्ट की गई शिकायतें लाइव ट्रैकिंग और अंक आवंटन के लिए ग्राम नागरिक फ़ीड पर प्रकाशित की जाती हैं।",

    // 6. Voice Dictation Assistant
    "Voice Dictation Assistant": "वॉयस श्रुतलेख सहायक",
    "Record your voice, and our real-time transcribing engine will write the complaint for you.": "अपनी आवाज रिकॉर्ड करें, और हमारा रीयल-टाइम अनुवाद इंजन आपके लिए शिकायत लिखेगा।",
    "Start Dictation": "श्रुतलेख शुरू करें",
    "Stop & Transcribe": "रोकें और ट्रांसक्राइब करें",
    "Speaking Real-time Transcript Preview:": "रीयल-टाइम ट्रांसक्रिप्ट पूर्वावलोकन बोलें:",
    "Listening... Start speaking to see text generation...": "सुन रहे हैं... टेक्स्ट निर्माण देखने के लिए बोलना शुरू करें...",
    "Your transcript text will generate here once you click Stop. You can manually tweak or edit it here as well.": "एक बार जब आप रोकें पर क्लिक करेंगे, तो आपका पाठ यहाँ उत्पन्न होगा। आप इसे मैन्युअल रूप से भी संपादित कर सकते हैं।",
    "Append to Description": "विवरण में जोड़ें",

    // 7. Social Hub & Leaderboard
    "Panchayat Social Wall": "पंचायत सोशल वॉल",
    "Village Community Corner": "ग्राम सामुदायिक कोना",
    "Interact with co-citizens, share community initiatives, and voice ideas. Only constructive topics permitted.": "सह-नागरिकों के साथ बातचीत करें, सामुदायिक पहलों को साझा करें और विचार व्यक्त करें। केवल सकारात्मक चर्चा की अनुमति है।",
    "Write something to the village community wall...": "ग्राम समुदाय की दीवार पर कुछ लिखें...",
    "Post to Wall": "दीवार पर पोस्ट करें",
    "Anonymous": "गुमनाम",
    "Likes": "पसंद",
    "Panchayat Leaderboard": "पंचायत लीडरबोर्ड",
    "Top Active Citizen Contributors": "शीर्ष सक्रिय नागरिक योगदानकर्ता",
    "Rankings are updated dynamically based on approved complaint filings (+15 points) and valid issue verifications (+5 points).": "स्वीकृत शिकायत दर्ज करने (+15 अंक) और वैध समस्या सत्यापन (+5 अंक) के आधार पर रैंकिंग गतिशील रूप से अपडेट की जाती है।",
    "Rank": "रैंक",
    "Citizen Name": "नागरिक का नाम",
    "Points Earned": "अर्जित अंक",
    "Issues": "मुद्दे",
    "Coins Earned": "अर्जित सिक्के",
    "Panchayat Level": "पंचायत स्तर",

    // 8. Notifications
    "Panchayat Notice Inbox": "पंचायत नोटिस इनबॉक्स",
    "Live dispatch SMS & push channels": "लाइव डिस्पैच एसएमएस और पुश चैनल",
    "Mark All as Read": "सभी को पढ़ा हुआ चिह्नित करें",
    "No notifications yet.": "अभी कोई सूचना नहीं है।",

    // General & Dashboard Profile
    "Ward": "वार्ड",
    "Coins": "सिक्के",
    "Ward Area": "वार्ड क्षेत्र",
    "Verified Citizen": "सत्यापित नागरिक",
    "District Commissioner": "जिला आयुक्त",
    "Panchayat Officer": "पंचायत अधिकारी",
    "Admin Controls": "प्रशासक नियंत्रण",

    // New Translations: Alerts, News, Social Hub, Admin
    "Live Alert & Notification logs": "लाइव अलर्ट और अधिसूचना लॉग",
    "This terminal tracks simulated multi-channel Push alerts and SMS dispatch logs in Nizamabad.": "यह टर्मिनल निजामाबाद में सिम्युलेटेड मल्टी-चैनल पुश अलर्ट और एसएमएस डिस्पैच लॉग को ट्रैक करता है।",
    "Mark all read": "सभी को पढ़ा हुआ चिह्नित करें",
    "SMS Logs": "एसएमएस लॉग",
    "Clear": "साफ करें",
    "Your Inbox is quiet. No notifications found.": "आपका इनबॉक्स शांत है। कोई सूचना नहीं मिली।",
    "Looking for Official Panchayat Announcements?": "आधिकारिक पंचायत घोषणाओं की तलाश है?",
    "Official Channel": "आधिकारिक चैनल",
    "While this Social Hub is a friendly space for open community discussion among citizens, official resolutions, emergency alerts, and department announcements have a dedicated home under the Alerts section.": "हालांकि यह सोशल हब नागरिकों के बीच खुली चर्चा के लिए एक अनुकूल जगह है, आधिकारिक प्रस्तावों, आपातकालीन अलर्ट और विभागीय घोषणाओं के लिए अलर्ट अनुभाग में एक समर्पित स्थान है।",
    "Check Alerts Section": "अलर्ट अनुभाग देखें",
    "Share Gram Discussion": "ग्राम चर्चा साझा करें",
    "What is happening in Nizamabad? Share announcements, alerts or opinions. Use #hashtags to tag topics, or @Sarpanch to notify officials.": "निजामाबाद में क्या हो रहा है? घोषणाएं, अलर्ट या विचार साझा करें। विषयों को टैग करने के लिए #hashtags का उपयोग करें, या अधिकारियों को सूचित करने के लिए @Sarpanch का उपयोग करें।",
    "Supports automatic hashtag recognition and staff tagging alerts.": "स्वचालित हैशटैग पहचान और स्टाफ टैगिंग अलर्ट का समर्थन करता है।",
    "Photo evidence ready": "फोटो सबूत तैयार है",
    "Video evidence evidence ready": "वीडियो सबूत तैयार है",
    "Attach Photo/Video": "फोटो/वीडियो संलग्न करें",
    "GPS Tagged": "जीपीएस टैग किया गया",
    "Tag Ward Location": "वार्ड स्थान टैग करें",
    "Clear Attach": "अटैचमेंट हटाएं",
    "Post anonymously (Mask identity)": "गुमनाम रूप से पोस्ट करें (पहचान छुपाएं)",
    "Publishing...": "प्रकाशित हो रहा है...",
    "Publish to Social Hub": "सोशल हब पर साझा करें",
    "Popular Panchayat Topics": "लोकप्रिय पंचायत विषय",
    "Panchayat Notice Board": "पंचायत नोटिस बोर्ड",
    "Panchayat News & Announcements": "पंचायत समाचार और घोषणाएं",
    "Stay informed with active community news, local utility schedules, and administrative developments.": "सक्रिय सामुदायिक समाचार, स्थानीय उपयोगिता कार्यक्रम और प्रशासनिक विकास के साथ सूचित रहें।",
    "Read Announcement": "घोषणा पढ़ें",
    "Released by": "द्वारा जारी",
    "Digital Portal Notice": "डिजिटल पोर्टल नोटिस",
    "This is an official digital broadcast issued by the Gram Panchayat administrative wing. For complaint registration or quick queries regarding this announcement, please use the citizen interactive desk.": "यह ग्राम पंचायत प्रशासनिक शाखा द्वारा जारी एक आधिकारिक डिजिटल प्रसारण है। इस घोषणा के संबंध में शिकायत पंजीकरण या त्वरित प्रश्नों के लिए, कृपया नागरिक इंटरैक्टिव डेस्क का उपयोग करें।",
    "Close Notice": "नोटिस बंद करें",
    "Sub-canal Drinking Water Pipeline Repair Completed": "उप-नहर पेयजल पाइपलाइन मरम्मत कार्य पूरा",
    "Annual Gram Panchayat Budget & Electrification Approval": "वार्षिक ग्राम पंचायत बजट और विद्युतीकरण अनुमोदन",
    "Digital Land Records & Aadhaar Seeding Desk Opens": "डिजिटल भूमि अभिलेख और आधार सीडिंग डेस्क खुला",
    "Monsoon Preparedness Audit: Drainage Cleansing Drive": "मानसून तैयारी ऑडिट: जल निकासी सफाई अभियान",
    "Utilities": "उपयोगिताएँ",
    "Government": "सरकार",
    "Development": "विकास",
    "Events": "आयोजन",
    "Gram Panchayat Online Services": "ग्राम पंचायत ऑनलाइन सेवाएं",
    "empowering village self-governance via Digital India Initiative.": "डिजिटल इंडिया पहल के माध्यम से ग्रामीण स्व-शासन को सशक्त बनाना।",
    "Report local problems, track updates and help build a better community together.": "स्थानीय समस्याओं की रिपोर्ट करें, अपडेट ट्रैक करें और मिलकर एक बेहतर समुदाय बनाने में मदद करें।",
    "How Panchayat Online Works": "पंचायत ऑनलाइन कैसे काम करता है",
    "1. Report": "1. रिपोर्ट करें",
    "Capture and report issues in your area with photos or videos.": "फोटो या वीडियो के साथ अपने क्षेत्र की समस्याओं को कैप्चर और रिपोर्ट करें।",
    "2. AI Categorization": "2. एआई वर्गीकरण",
    "Our AI automatically categorizes and assigns the issue.": "हमारा एआई स्वचालित रूप से समस्या को वर्गीकृत और आवंटित करता है।",
    "3. Track": "3. ट्रैक करें",
    "Track the status of your reported issue in real time.": "वास्तविक समय में अपनी रिपोर्ट की गई समस्या की स्थिति को ट्रैक करें।",
    "4. Resolved": "4. समाधान किया गया",
    "Get updates and notifications when the issue is resolved.": "समस्या का समाधान होने पर अपडेट और सूचनाएं प्राप्त करें।",
    "Stay Updated": "अपडेट रहें",
    "Subscribe to get updates and important announcements.": "अपडेट और महत्वपूर्ण घोषणाएं प्राप्त करने के लिए सदस्यता लें।",
    "Enter your email": "अपना ईमेल दर्ज करें",
    "Subscribed!": "सदस्यता ली गई!",
    "Subscribe": "सदस्यता लें",
    "Follow Us": "हमारा अनुसरण करें",
    "Panchayat Online. All rights reserved.": "पंचायत ऑनलाइन। सर्वाधिकार सुरक्षित।",
    "Help Center": "सहायता केंद्र",
    "Back": "पीछे",
    "Access Secure Portal": "सुरक्षित पोर्टल तक पहुंचें",
    "Select your access role below to sign in or get started.": "साइन इन करने या शुरू करने के लिए नीचे अपनी पहुंच भूमिका चुनें।",
    "Enter as Citizen": "नागरिक के रूप में प्रवेश करें",
    "Enter as Panchayat Officer": "पंचायत अधिकारी के रूप में प्रवेश करें",
    "Citizen Access": "नागरिक पहुंच",
    "Officer Access": "अधिकारी पहुंच",
    "OTP Verification": "ओटीपी सत्यापन",
    "Enter your email credentials to access your secure profile.": "अपने सुरक्षित प्रोफ़ाइल तक पहुँचने के लिए अपने ईमेल क्रेडेंशियल दर्ज करें।",
    "Authenticate instantly with a mobile verification code.": "मोबाइल सत्यापन कोड के साथ तुरंत प्रमाणित करें।",
    "Forgot?": "भूल गए?",
    "Verifying Access...": "पहुंच सत्यापित की जा रही है...",
    "Secure Sign In": "सुरक्षित साइन इन",
    "Sending OTP...": "ओटीपी भेजा जा रहा है...",
    "Send OTP Code": "ओटीपी कोड भेजें",
    "Change Mobile": "मोबाइल बदलें",
    "Demo OTP: 1234": "डेमो ओटीपी: 1234",
    "Verifying OTP...": "ओटीपी सत्यापित किया जा रहा है...",
    "Verify & Login": "सत्यापित करें और लॉगिन करें",
    "Or Continue With": "या इसके साथ जारी रखें",
    "This calling feature works better in mobile phone": "यह कॉलिंग सुविधा मोबाइल फोन में बेहतर काम करती है",
    "Panchayat Emergency Helpline": "पंचायत आपातकालीन हेल्पलाइन",
    "Initiate direct calls to village administration and maintenance directors instantly.": "ग्राम प्रशासन और रखरखाव निदेशकों को तुरंत सीधे कॉल करें।",
    "Simulate Call": "कॉल का अनुकरण करें",
    "Direct Dialer Link": "सीधा डायलर लिंक",
    "Emergency Warning:": "आपातकालीन चेतावनी:",
    "If you are calling to report immediate threats (like active live electrical cables sparked by storms, major canal breaches flooding houses), please dial the Sarpanch or Sanitation officer immediately to dispatch emergency response squads.": "यदि आप तत्काल खतरों (जैसे तूफान से सक्रिय लाइव बिजली के तार, घरों में बाढ़ लाने वाली प्रमुख नहर दरारें) की रिपोर्ट करने के लिए कॉल कर रहे हैं, तो कृपया आपातकालीन प्रतिक्रिया टीमों को भेजने के लिए तुरंत सरपंच या स्वच्छता अधिकारी को कॉल करें।",
    "Smt. Rajeshwari Devi": "श्रीमती राजेश्वरी देवी",
    "Gram Panchayat Sarpanch (President)": "ग्राम पंचायत सरपंच (अध्यक्ष)",
    "Shri Mohan Rao": "श्री मोहन राव",
    "Panchayat Secretary (Administrative Head)": "पंचायत सचिव (प्रशासनिक प्रमुख)",
    "Smt. Lakshmi Bai": "श्रीमती लक्ष्मी बाई",
    "Health & Sanitation Inspector": "स्वास्थ्य एवं स्वच्छता निरीक्षक",
    "Shri Venkatesh Goud": "श्री वेंकटेश गौड़",
    "Water Works & Electrical Engineer": "जल कार्य एवं विद्युत अभियंता",
    "Shri Ramesh Kumar": "श्री रमेश कुमार",
    "Ward 1 & 2 Civic Representative": "वार्ड 1 और 2 नागरिक प्रतिनिधि",
    "Available": "उपलब्ध",
    "In Office": "कार्यालय में",
    "On Field Patrol": "फील्ड गश्ती पर",
    "Meeting": "बैठक में"
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("panchayat_lang");
    return (saved === "te" || saved === "hi" ? saved : "en") as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("panchayat_lang", lang);
  };

  const t = (text: string): string => {
    if (language === "en") return text;
    const cleanText = text.trim();
    
    // Exact match
    const translated = TRANSLATIONS[language]?.[cleanText];
    if (translated) return translated;

    // Partial match fallback for longer combined text or close patterns
    const entries = Object.entries(TRANSLATIONS[language] || {}) as [string, string][];
    for (const [key, val] of entries) {
      if (cleanText.toLowerCase().includes(key.toLowerCase())) {
        return cleanText.replace(new RegExp(key, "gi"), val);
      }
    }

    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
